name: Release and Publish NumberScript

on:
  release:
    types: [published]   # Runs when a GitHub Release is published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Install publishing tools
        run: |
          npm install -g vsce ovsx

      - name: Publish to VS Code Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

      - name: Publish to Open VSX
        run: ovsx publish -p ${{ secrets.OVSX_PAT }}
