name: Publish Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Commit uncommitted changes if any
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if ! git diff --quiet || ! git diff --cached --quiet; then
            git add -A
            git commit -m "CI: Auto-commit uncommitted changes [skip ci]"
          else
            echo "No changes to commit."
          fi

      - name: Compile TypeScript
        run: npm run build

      - name: Bump version patch
        run: npm version patch -m "CI: Bump version to %s [skip ci]"

      - name: Package VS Code Extension
        run: npx @vscode/vsce package

      - name: Publish VS Code Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx @vscode/vsce publish
