name: Auto Publish VS Code Extension

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Compile TypeScript
      - name: Compile extension
        run: npm run compile

      # 5. Bump version automatically
      - name: Bump version
        run: |
          npm version patch -m "CI: Bump version to %s [skip ci]"

      # 6. Package VS Code extension
      - name: Package extension
        run: npx @vscode/vsce package

      # 7. Publish extension
      - name: Publish extension
        run: npx @vscode/vsce publish --pat ${{ secrets.VSCE_PAT }}
