name: Publish VS Code Extension

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Commit any uncommitted changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git diff --cached --quiet || git commit -m "chore: auto-commit changes before version bump [skip ci]"

      - name: Bump version
        run: npm version patch -m "CI: Bump version to %s [skip ci]"

      - name: Publish VSCE package
        run: npx @vscode/vsce publish
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
