name: Publish NumberScript Extension

on:
  push:
    tags:
      - 'v*.*.*'   # Triggers workflow on version tags like v1.0.0, v1.1.0, etc.

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Install vsce
        run: npm install -g vsce

      - name: Publish to VS Code Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}

